"use client";
import { useEffect, useState } from "react";
import NavBar from "../Components/Shared/NavBar";

// export const metadata = {
//   title: "Super Shop",
//   description: "Generated by Next.js"
// };

export default function CommonLayout({ children }) {
  const [isNavbarVisible, setIsNavbarVisible] = useState(true);
  const [lastScrollY, setLastScrollY] = useState(0);

  useEffect(() => {
    const handleScroll = () => {
      const currentScrollY = window.scrollY;

      // Show navbar when scrolling up, hide when scrolling down
      if (currentScrollY < lastScrollY) {
        setIsNavbarVisible(true);
      } else {
        setIsNavbarVisible(false);
      }

      setLastScrollY(currentScrollY);
    };

    // Listen for scroll events
    window.addEventListener("scroll", handleScroll);

    return () => {
      window.removeEventListener("scroll", handleScroll);
    };
  }, [lastScrollY]);

  return (
    <html lang="en">
      <body>
        <div
          className={`sticky top-0 left-0  w-full transition-transform duration-300 ${
            isNavbarVisible
              ? "transform translate-y-0"
              : "transform -translate-y-full"
          }`}
        >
          <NavBar />
        </div>
        {children}
      </body>
    </html>
  );
}
